CREATE TABLE user (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) UNIQUE NOT NULL,
    hashed_password VARCHAR(50) NOT NULL,
    profil_photo VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE trail (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    length VARCHAR(50) NOT NULL,
    difficulty INT NOT NULL,
    photo VARCHAR(255) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE comment (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    comment TEXT NOT NULL,
    user_id INTEGER UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id),
    trail_id INTEGER UNSIGNED NOT NULL,
    FOREIGN KEY (trail_id) REFERENCES trail (id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);